FROM node:lts
WORKDIR /usr/local/app

ENV NODE_ENV=$NODE_ENV
#ENV NODE_PATH=/node_modules
#ENV PATH $PATH:/node_modules/.bin

COPY ["./next005/package*.json", "/usr/local/app/"]
RUN npm install && npm cache verify --force

#RUN npm install -g nodemon
#CMD ["sh"]
